import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [bdate, setBdate] = useState("");
  const [cnumber, setCnumber] = useState("");

  const handleAdd = (e) => {
    e.preventDefault();
    console.log({ name, email, bdate, cnumber });
  };
  return (
    <>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h2>CRUD</h2>

        <div className="field-wrap">
          <input
            type="text"
            placeholder="name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
        </div>
        <div className="field-wrap">
          <input
            type="email"
            placeholder="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>
        <div className="field-wrap">
          <input
            type="date"
            placeholder="birthdate"
            value={bdate}
            onChange={(e) => setBdate(e.target.value)}
          />
        </div>
        <div className="field-wrapper">
          <input
            type="number"
            placeholder="contact number"
            value={cnumber}
            onChange={(e) => setCnumber(e.target.value)}
          />
        </div>
        <button onClick={handleAdd}>submit</button>
      </main>
    </>
  );
}
